import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import StoreProvider from "@/components/store-provider";
import StartUp from "@/components/startup";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="html">
      <head>
        <style suppressHydrationWarning>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
      </head>
      <body className=".body">
        <div id="backdrop"></div>
        <StoreProvider>
          <StartUp />
          <Navbar />
          {children}
        </StoreProvider>
        <div id="footer"></div>
      </body>
    </html>
  );
}
